version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - kafka_network
    

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - kafka_network

  api-server:
    image: new_bar_test
    depends_on:
      kafka:
        condition: service_started
      mongo:
        condition: service_started
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - KAFKA_BROKER=kafka:9092
    ports:
      - "5000:5000"
    networks:
      - kafka_network

  client-web-server:
    image: bar_front
    depends_on:
      api-server:
        condition: service_started
    environment:
      - API_SERVER_URL=http://api-server:5000
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8000:8000"
    networks:
      - kafka_network
      
      
networks:
  kafka_network:
    driver: bridge

volumes: 
  mongodb_data:
  
