name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  git_hash: $(git rev-parse --short "$GITHUB_SHA")
  git_branch: ${GITHUB_REF#refs/heads/}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build ./api -t barminz/argo_app_api:${{ env.git_branch }}.${{ env.git_hash }}
        docker build ./client -t barminz/argo_app_client:${{ env.git_branch }}.${{ env.git_hash }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push current version
      run: |
        docker push barminz/argo_app_api:${{ env.git_branch }}.${{ env.git_hash }}
        docker push barminz/argo_app_client:${{ env.git_branch }}.${{ env.git_hash }}

    - name: Tag latest
      run: |
        docker tag barminz/argo_app_api:${{ env.git_branch }}.${{ env.git_hash }} barminz/argo_app_api:latest
        docker tag barminz/argo_app_client:${{ env.git_branch }}.${{ env.git_hash }} barminz/argo_app_client:latest

    - name: Push latest
      run: |
        docker push barminz/argo_app_api:latest
        docker push barminz/argo_app_client:latest
