name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  git_hash: $(git rev-parse --short "$GITHUB_SHA")
  git_branch: ${GITHUB_REF#refs/heads/}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build ./api -t avkh12345/pmk_frontend:${{ env.git_branch }}.${{ env.git_hash }}
        docker build ./client -t avkh12345/pmk_backend:${{ env.git_branch }}.${{ env.git_hash }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push current version
      run: |
        docker push avkh12345/pmk_frontend:${{ env.git_branch }}.${{ env.git_hash }}
        docker push avkh12345/pmk_backend:${{ env.git_branch }}.${{ env.git_hash }}

    - name: Tag latest
      run: |
        docker tag avkh12345/pmk_frontend:${{ env.git_branch }}.${{ env.git_hash }} avkh12345/pmk_frontend:latest
        docker tag avkh12345/pmk_backend:${{ env.git_branch }}.${{ env.git_hash }} avkh12345/pmk_backend:latest

    - name: Push latest
      run: |
        docker push avkh12345/pmk_frontend:latest
        docker push avkh12345/pmk_backend:latest
